### ISSUE TITLE
Некорректно отображается меню, если поле location начинается с /

### ISSUE THREAD

**Issue by apoddubny** [SEAFTeam/seaf-dzo#36]
Бекенд докхаб v3.0.3

![image](https://github.com/SEAFTeam/seaf-dzo/assets/1941030/00880671-06da-4d47-95e8-84742a7cb99c)
![image](https://github.com/SEAFTeam/seaf-dzo/assets/1941030/f5b25f20-c417-462a-aaf2-bbde7bc179c5)

**Comment by rpiontik** [comment]
Эта фича начала работать с версии 3.4.0
